---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: folding-at-home
  labels:
    app: folding-at-home
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: folding-at-home
  template:
    metadata:
      labels:
        app: folding-at-home
    spec:
      containers:
        - name: folding-at-home
          image: stefancrain/folding-at-home:7.5.1-gpu
          imagePullPolicy: IfNotPresent
          command: ["/bin/tini", "--", "/usr/bin/FAHClient", "--web-allow=0/0:7396", "--allow=0/0:7396", "--smp=true"]
          args: ["--user=<YOUR_NAME>", "--team=241985", "--gpu=true", "--power=full", "--gpu-usage=50"]
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 2Gi
#               gpu.intel.com/i915: 1
#       affinity:
#         nodeAffinity:
#           requiredDuringSchedulingIgnoredDuringExecution:
#             nodeSelectorTerms:
#             - matchExpressions:
#               - key: homelab.gpu/type
#                 operator: In
#                 values: 
#                   - "intel"
---
apiVersion: v1
kind: Service
metadata:
  name: folding-at-home
spec:
  selector:
    app: folding-at-home
  type: NodePort
  ports:
    - port: 7396
      nodePort: 30160
      targetPort: 7396
