---
name: latest

on:
  push:
    paths:
      - ".github/workflows/**"
      - "build/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "build/**"
    branches:
      - main
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: $(cat build/fah-public.version)
      BUILD_DATE: $(date -u +'%Y-%m-%dT%H:%M:%SZ')
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to GitHub Docker Registry
        run: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build beta Image
        if: github.ref == 'refs/heads/beta'
        run: |
          docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --build-arg=BUILD_DATE=${{ env.VERSION_MAJOR }} \
            --build-arg=VCS_REF=${{ github.sha }} \
            --target mini \
            --tag stefancrain/folding-at-home-mini:latest-beta \
            --tag stefancrain/folding-at-home-mini:${{ env.VERSION }}-beta \
            -f ./build/Dockerfile \
            ./build/ \
            --push
          docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --build-arg=BUILD_DATE=${{ env.VERSION_MAJOR }} \
            --build-arg=VCS_REF=${{ github.sha }} \
            --tag stefancrain/folding-at-home:latest-beta \
            --tag stefancrain/folding-at-home:${{ env.VERSION }}-beta \
            -f ./build/Dockerfile \
            ./build/ \
            --push

      - name: Build stable Image
        if: github.ref == 'refs/heads/main'
        run: |
          docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --build-arg=BUILD_DATE=${{ env.VERSION_MAJOR }} \
            --build-arg=VCS_REF=${{ github.sha }} \
            --target mini \
            --tag stefancrain/folding-at-home-mini:stable \
            --tag stefancrain/folding-at-home-mini:${{ env.VERSION }} \
            -f ./build/Dockerfile \
            ./build/ \
            --push
          docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --build-arg=BUILD_DATE=${{ env.VERSION_MAJOR }} \
            --build-arg=VCS_REF=${{ github.sha }} \
            --tag stefancrain/folding-at-home:stable \
            --tag stefancrain/folding-at-home:${{ env.VERSION }} \
            -f ./build/Dockerfile \
            ./build/ \
            --push
